cxx_binary(
  name = 'tests',
  header_namespace = '',
  headers = subdir_glob([
    ('', '**/*.h'),
  ]),
  srcs = glob([
    '**/*.cc',
  ]),
  compiler_flags = [
    '-std=c++14',
  ],
  deps = [
    '//:immutable-cpp',
  ],
)
